apiVersion: apps/v1
kind: Deployment
metadata:
  name: good-deployment
  namespace: production
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: acrdwe001.azurecr.io/kuard-amd64:1